KINECT_SRC_ADDR = 'cwc1'
KINECT_SKELETON_PORT = 8000
KINECT_HEAD_DEPTH_PORT = 8000
KINECT_DEPTH_PORT = 8000

FUSION_SRC_ADDR = 'blue'
FUSION_INPUT_PORT = 9125
FUSION_BRANDEIS_PORT = 9126
FUSION_GUI_PORT = 9127

FUSION_LEFT_HAND_ID = 2
FUSION_RIGHT_HAND_ID = 4
FUSION_HEAD_ID = 8


